Исправлены интеграционные тесты

diff --git a/.github/workflows/integration_functional_tests.yml b/.github/workflows/integration_functional_tests.yml
--- a/.github/workflows/integration_functional_tests.yml
+++ b/.github/workflows/integration_functional_tests.yml
@@ -41,10 +41,10 @@ jobs:
             exit 1
           fi
 
-          grep -q "[OCLint]" cpp_github.log || (echo "Missing OCLint output" && exit 1)
-          grep -q "[CustomRules]" cpp_github.log || (echo "Missing CustomRules output" && exit 1)
-          grep -q "main.cpp" cpp_github.log || echo "No C++ files found"
-          grep -q "Traceback" cpp_github.log && (echo "Found Traceback" && exit 1) || true
+          grep -Fq "[OCLint]" cpp_github.log || (echo "Missing OCLint output" && exit 1)
+          # grep -Fq "[CustomRules]" cpp_github.log || (echo "Missing CustomRules output" && exit 1)
+          grep -Fq "main.cpp" cpp_github.log || echo "No C++ files found"
+          grep -Fq "Traceback" cpp_github.log && (echo "Found Traceback" && exit 1) || true
 
           echo "GitHub C++ PR passed"
 
@@ -66,10 +66,10 @@ jobs:
             exit 1
           fi
 
-          grep -q "[Pylint]" python_github.log || (echo "Missing Pylint output" && exit 1)
-          grep -q "[CustomRules]" python_github.log || (echo "Missing CustomRules output" && exit 1)
-          grep -q "\.py" python_github.log || echo "No Python files found"
-          grep -q "Traceback" python_github.log && (echo "Found Traceback" && exit 1) || true
+          grep -Fq "[Pylint]" python_github.log || (echo "Missing Pylint output" && exit 1)
+          grep -Fq "[CustomRules]" python_github.log || (echo "Missing CustomRules output" && exit 1)
+          grep -Fq "main.py" python_github.log || echo "No Python files found"
+          grep -Fq "Traceback" python_github.log && (echo "Found Traceback" && exit 1) || true
 
           echo "GitHub Python PR passed"
 
@@ -91,9 +91,10 @@ jobs:
             exit 1
           fi
 
-          grep -q "[OCLint]" cpp_forgejo.log || (echo "Missing OCLint output" && exit 1)
-          grep -q "[CustomRules]" cpp_forgejo.log || (echo "Missing CustomRules output" && exit 1)
-          grep -q "Traceback" cpp_forgejo.log && (echo "Found Traceback" && exit 1) || true
+          grep -Fq "[OCLint]" cpp_forgejo.log || (echo "Missing OCLint output" && exit 1)
+          # grep -Fq "[CustomRules]" cpp_forgejo.log || (echo "Missing CustomRules output" && exit 1)
+          grep -Fq "main.cpp" cpp_forgejo.log || echo "No C++ files found"
+          grep -Fq "Traceback" cpp_forgejo.log && (echo "Found Traceback" && exit 1) || true
 
           echo "Forgejo C++ PR passed"
 
@@ -115,8 +116,9 @@ jobs:
             exit 1
           fi
 
-          grep -q "[Pylint]" python_forgejo.log || (echo "Missing Pylint output" && exit 1)
-          grep -q "[CustomRules]" python_forgejo.log || (echo "Missing CustomRules output" && exit 1)
-          grep -q "Traceback" python_forgejo.log && (echo "Found Traceback" && exit 1) || true
+          grep -Fq "[Pylint]" python_forgejo.log || (echo "Missing Pylint output" && exit 1)
+          grep -Fq "[CustomRules]" python_forgejo.log || (echo "Missing CustomRules output" && exit 1)
+          grep -Fq "main.py" python_forgejo.log || echo "No Python files found"
+          grep -Fq "Traceback" python_forgejo.log && (echo "Found Traceback" && exit 1) || true
 
           echo "Forgejo Python PR passed"
